[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/capi",
    "crates/cli",
    "crates/python",
]

[workspace.package]
version = "1.5.3"
authors = ["Musharraf Omer<ibnomer2011@hotmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
description = "Arabic-text diacritic restoration using neural networks"
repository = "https://github.com/ZirekHQ/dengjen-tashkeel"
documentation = "https://github.com/ZirekHQ/dengjen-tashkeel"

[workspace.metadata.dist]
cargo-dist-version = "0.32.0"
ci = "github"
allow-dirty = ["ci"]
installers = ["shell", "powershell", "msi"]
targets = ["aarch64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
install-path = "CARGO_HOME"
install-updater = false
msvc-crt-static = false
[workspace.metadata.dist.github-custom-runners]
x86_64-unknown-linux-gnu = "ubuntu-latest"
global = "ubuntu-24.04"

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1

[profile.dist]
inherits = "release"
lto = "thin"
