[package]
name = "dengjen-tashkeel-python"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
documentation.workspace = true

[lib]
name = "dengjen_tashkeel_py"
crate-type = ["cdylib"]

[features]
default = ["ort"]
ort = ["dengjen-tashkeel/ort-static"]
ort-dylib = ["dengjen-tashkeel/ort-dylib"]
extension-module = ["pyo3/extension-module"]

[dependencies]
log = "0.4.18"

[dependencies.pyo3]
version = "0.29"
features = ["abi3-py39"]

[dev-dependencies]
tempfile = "3"

[dev-dependencies.pyo3]
version = "0.29"
features = ["auto-initialize"]

[dependencies.dengjen-tashkeel]
version = "1.5.2"
path = "../core"
default-features = false
